### ISSUE TITLE
Unable to use @BeforeClass or @BeforeSuite

### ISSUE THREAD

**Issue by Rameshwar-Juptimath** [hemanthsridhar/WebAppFramework#3]
Hi Hemanth,

We will not be able to use @BeforeClass or @BeforeSuite to perform any steps before we continue with the test methods. If any code, that utilizes the created driver instance is written in @BeforeClass/Suite, you will end up in an NPE.

This is because driver creation code is annotated as @BeforeMethod which gets executed after @BeforeClass/Suite methods.

**Comment by hemanthsridhar** [comment]
The framework is developed in such a way that it restricts the use of these annotations to reduce flakiness in the test run. Instead of using @BeforClass/Suite, please try to use @BeforeGroups or any other alternative.
Closing the issue.
